className="absolute inset-0 bg-black/30 flex items-center justify-center">▶</div></div><div className="text-xs mt-1 font-bold truncate">{m.title}</div></div>)}</div></div>

<div className="px-4 mt-6"><div className="flex justify-between items-center"><h3 className="font-bold border-l-2 border-[#FFC91A] pl-3">🎬 Movies</h3><button onClick={()=>setTab("movies")} className="text-xs text-[#FFC91A]">See all →</button></div><div className="flex gap-3 mt-3 overflow-x-auto">{mov.map(m=><div key={m.id} onClick={()=>setPlay(m)} className="min-w-[120px] cursor-pointer"><div className="h-[160px] rounded-xl bg-cover" style={{backgroundImage:url(${m.img})}}></div><div className="text-[11px] mt-1 font-bold truncate">{m.title}</div><div className="text-[9px] text-white/30">{m.cat} • {m.year}</div></div>)}</div></div>

<div className="px-4 mt-6"><div className="flex justify-between items-center"><h3 className="font-bold border-l-2 border-[#FFC91A] pl-3">📺 Series</h3><button onClick={()=>setTab("series")} className="text-xs text-[#FFC91A]">See all →</button></div><div className="flex gap-3 mt-3 overflow-x-auto">{ser.map(m=><div key={m.id} onClick={()=>setPlay(m)} className="min-w-[120px] cursor-pointer"><div className="h-[160px] rounded-xl bg-cover" style={{backgroundImage:url(${m.img})}}></div><div className="text-[11px] mt-1 font-bold truncate">{m.title}</div><div className="text-[9px] text-white/30">{m.year}</div></div>)}</div></div>
</div>
)}

{tab==="movies" && (<div className="p-4"><h1 className="text-2xl font-black">🎬 Movies ({mov.length})</h1><div className="grid grid-cols-3 gap-3 mt-4">{mov.map(m=><div key={m.id} onClick={()=>setPlay(m)} className="bg-[#11182D] rounded-xl overflow-hidden cursor-pointer"><div className="h-[150px] bg-cover" style={{backgroundImage:url(${m.img})}}></div><div className="p-2"><div className="text-xs font-bold truncate">{m.title}</div><div className="text-[9px] text-white/30">{m.year}</div></div></div>)}</div></div>)}
{tab==="series" && (<div className="p-4"><h1 className="text-2xl font-black">📺 Series ({ser.length})</h1><div className="grid grid-cols-3 gap-3 mt-4">{ser.map(m=><div key={m.id} onClick={()=>setPlay(m)} className="bg-[#11182D] rounded-xl overflow-hidden cursor-pointer"><div className="h-[150px] bg-cover" style={{backgroundImage:url(${m.img})}}></div><div className="p-2"><div className="text-xs font-bold truncate">{m.title}</div><div className="text-[9px] text-white/30">{m.year}</div></div></div>)}</div></div>)}
{tab==="live" && (<div className="p-4"><h1 className="text-2xl font-black">🔴 Live TV Platforms ({live.length})</h1><div className="grid grid-cols-2 gap-3 mt-4">{live.map(m=><div key={m.id} onClick={()=>setPlay(m)} className="bg-[#11182D] rounded-xl overflow-hidden border border-red-500/20 cursor-pointer"><div className="h-[110px] bg-cover relative" style={{backgroundImage:url(${m.img})}}><span className="absolute top-2 left-2 bg-red-600 text-[9px] px-2 py-1 rounded-full">● LIVE</span><div className="absolute inset-0 flex items-center justify-center text-2xl">▶</div></div><div className="p-2 text-xs font-bold">{m.title}</div></div>)}</div></div>)}

{tab==="profile" && (<div className="p-4">
<div className="bg-gradient-to-br from-[#11182D] to-[#0B1120] rounded-[24px] p-6 text-center border border-[#FFC91A]/20">
<div className="w-20 h-20 bg-gradient-to-br from-[#FFC91A] to-yellow-600 rounded-full mx-auto flex items-center justify-center text-2xl font-black text-black">{isLogged? userName[0] : "Q"}</div>
<div className="font-black text-xl mt-3">{isLogged? userName : "Quraish Mino 👑"}</div><div className="text-[
